In [1]:
ls

Untitled.ipynb          listings.csv            reviews 2.csv
calendar.csv            neighbourhoods.csv      reviews.csv
listings 2.csv          neighbourhoods.geojson

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [155]:
calendar = pd.read_csv('calendar.csv')
reviews_1 = pd.read_csv('reviews.csv')
reviews_2 = pd.read_csv('reviews_2.csv')
listings = pd.read_csv('listings.csv')
listings_2 = pd.read_csv('listings_2.csv')
neighborhoods = pd.read_csv('neighbourhoods.csv')
df_sf = pd.read_csv('listings_sf.csv')

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [156]:
calendar.shape, reviews_1.shape, reviews_2.shape, listings.shape, listings_2.shape, neighborhoods.shape, df_sf.shape

((2981670, 7),
 (306085, 2),
 (306085, 6),
 (8169, 16),
 (8169, 106),
 (77, 2),
 (7575, 106))

In [17]:
calendar.head(100)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1313847,2019-05-19,t,$60.00,$60.00,32,1125
1,2384,2019-05-19,f,$70.00,$70.00,2,89
2,2384,2019-05-20,f,$70.00,$70.00,2,89
3,2384,2019-05-21,f,$70.00,$70.00,2,89
4,2384,2019-05-22,f,$70.00,$70.00,2,89
5,2384,2019-05-23,f,$70.00,$70.00,2,89
6,2384,2019-05-24,f,$70.00,$70.00,2,89
7,2384,2019-05-25,f,$70.00,$70.00,2,89
8,2384,2019-05-26,f,$70.00,$70.00,2,89
9,2384,2019-05-27,f,$70.00,$70.00,2,89
10,2384,2019-05-28,t,$70.00,$70.00,2,89
11,2384,2019-05-29,t,$70.00,$70.00,2,89
12,2384,2019-05-30,t,$70.00,$70.00,2,89
13,2384,2019-05-31,t,$70.00,$70.00,2,89
14,2384,2019-06-01,f,$75.00,$75.00,2,89
15,2384,2019-06-02,f,$75.00,$75.00,2,89
16,2384,2019-06-03,t,$75.00,$75.00,2,89
17,2384,2019-06-04,t,$75.00,$75.00,2,89
18,2384,2019-06-05,t,$75.00,$75.00,2,89
19,2384,2019-06-06,t,$75.00,$75.00,2,89
20,2384,2019-06-07,f,$75.00,$75.00,2,89
21,2384,2019-06-08,f,$75.00,$75.00,2,89
22,2384,2019-06-09,t,$75.00,$75.00,2,89
23,2384,2019-06-10,t,$75.00,$75.00,2,89
24,2384,2019-06-11,t,$75.00,$75.00,2,89
25,2384,2019-06-12,t,$75.00,$75.00,2,89
26,2384,2019-06-13,t,$75.00,$75.00,2,89
27,2384,2019-06-14,f,$75.00,$75.00,2,89
28,2384,2019-06-15,f,$75.00,$75.00,2,89
29,2384,2019-06-16,t,$75.00,$75.00,2,89
30,2384,2019-06-17,t,$75.00,$75.00,2,89
31,2384,2019-06-18,t,$75.00,$75.00,2,89
32,2384,2019-06-19,t,$75.00,$75.00,2,89
33,2384,2019-06-20,t,$75.00,$75.00,2,89
34,2384,2019-06-21,t,$75.00,$75.00,2,89
35,2384,2019-06-22,t,$75.00,$75.00,2,89
36,2384,2019-06-23,t,$75.00,$75.00,2,89
37,2384,2019-06-24,t,$75.00,$75.00,2,89
38,2384,2019-06-25,t,$75.00,$75.00,2,89
39,2384,2019-06-26,t,$75.00,$75.00,2,89
40,2384,2019-06-27,f,$70.00,$70.00,2,89
41,2384,2019-06-28,f,$70.00,$70.00,2,89
42,2384,2019-06-29,f,$70.00,$70.00,2,89
43,2384,2019-06-30,f,$70.00,$70.00,2,89
44,2384,2019-07-01,f,$70.00,$70.00,2,89
45,2384,2019-07-02,f,$70.00,$70.00,2,89
46,2384,2019-07-03,t,$75.00,$75.00,2,89
47,2384,2019-07-04,t,$75.00,$75.00,2,89
48,2384,2019-07-05,t,$80.00,$80.00,2,89
49,2384,2019-07-06,t,$80.00,$80.00,2,89
50,2384,2019-07-07,t,$80.00,$80.00,2,89
51,2384,2019-07-08,t,$75.00,$75.00,2,89
52,2384,2019-07-09,t,$75.00,$75.00,2,89
53,2384,2019-07-10,t,$75.00,$75.00,2,89
54,2384,2019-07-11,t,$75.00,$75.00,2,89
55,2384,2019-07-12,t,$75.00,$75.00,2,89
56,2384,2019-07-13,t,$75.00,$75.00,2,89
57,2384,2019-07-14,t,$75.00,$75.00,2,89
58,2384,2019-07-15,t,$75.00,$75.00,2,89
59,2384,2019-07-16,t,$75.00,$75.00,2,89
60,2384,2019-07-17,t,$75.00,$75.00,2,89
61,2384,2019-07-18,t,$75.00,$75.00,2,89
62,2384,2019-07-19,t,$75.00,$75.00,2,89
63,2384,2019-07-20,t,$75.00,$75.00,2,89
64,2384,2019-07-21,t,$75.00,$75.00,2,89
65,2384,2019-07-22,t,$75.00,$75.00,2,89
66,2384,2019-07-23,t,$75.00,$75.00,2,89
67,2384,2019-07-24,t,$75.00,$75.00,2,89
68,2384,2019-07-25,t,$75.00,$75.00,2,89
69,2384,2019-07-26,t,$75.00,$75.00,2,89
70,2384,2019-07-27,t,$75.00,$75.00,2,89
71,2384,2019-07-28,t,$75.00,$75.00,2,89
72,2384,2019-07-29,t,$75.00,$75.00,2,89
73,2384,2019-07-30,t,$75.00,$75.00,2,89
74,2384,2019-07-31,t,$75.00,$75.00,2,89
75,2384,2019-08-01,t,$90.00,$90.00,2,89
76,2384,2019-08-02,t,$90.00,$90.00,2,89
77,2384,2019-08-03,t,$90.00,$90.00,2,89
78,2384,2019-08-04,t,$90.00,$90.00,2,89
79,2384,2019-08-05,f,$50.00,$50.00,2,89
80,2384,2019-08-06,f,$50.00,$50.00,2,89
81,2384,2019-08-07,f,$50.00,$50.00,2,89
82,2384,2019-08-08,f,$50.00,$50.00,2,89
83,2384,2019-08-09,t,$70.00,$70.00,2,89
84,2384,2019-08-10,t,$80.00,$80.00,2,89
85,2384,2019-08-11,t,$70.00,$70.00,2,89
86,2384,2019-08-12,f,$50.00,$50.00,2,89
87,2384,2019-08-13,f,$50.00,$50.00,2,89
88,2384,2019-08-14,f,$50.00,$50.00,2,89
89,2384,2019-08-15,f,$50.00,$50.00,2,89
90,2384,2019-08-16,t,$75.00,$75.00,2,89
91,2384,2019-08-17,t,$75.00,$75.00,2,89
92,2384,2019-08-18,t,$75.00,$75.00,2,89
93,2384,2019-08-19,f,$50.00,$50.00,2,89
94,2384,2019-08-20,f,$50.00,$50.00,2,89
95,2384,2019-08-21,f,$50.00,$50.00,2,89
96,2384,2019-08-22,f,$50.00,$50.00,2,89
97,2384,2019-08-23,t,$75.00,$75.00,2,89
98,2384,2019-08-24,t,$75.00,$75.00,2,89
99,2384,2019-08-25,t,$75.00,$75.00,2,89

In [18]:
calendar['listing_id'].nunique()

8169

In [19]:
reviews_1.head()

   listing_id        date
0        2384  2015-01-09
1        2384  2015-03-24
2        2384  2015-04-19
3        2384  2015-04-30
4        2384  2015-05-04

In [20]:
reviews_2.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2384,25218143,2015-01-09,14385014,Ivan,it's a wonderful trip experience. I didn't exc...
1,2384,28475392,2015-03-24,16241178,Namhaitou,This is my first trip using Airbnb. I was a li...
2,2384,30273263,2015-04-19,26101401,Patrick,The reservation was canceled 80 days before ar...
3,2384,30974202,2015-04-30,26247321,Cristina,Sólo puedo decir cosas buenas de Rebecca. La h...
4,2384,31363208,2015-05-04,31293837,SuJung,Rebecca was an absolutely wonderful host.\r\n\...

In [8]:
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,Hyde Park - Walk to UChicago/Metra to McCormic...,2613,Rebecca,NaN,Hyde Park,41.78886,-87.58671,Private room,50,2,149,2019-05-17,2.81,1,316
1,4505,We're back. 365 Great Reviews. 1 bad one.,5775,Craig & Kathleen,NaN,South Lawndale,41.85495,-87.69696,Entire home/apt,117,2,368,2019-05-05,2.96,1,310
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90289,-87.68182,Entire home/apt,80,2,338,2019-05-05,2.81,1,309
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,NaN,Lincoln Park,41.91769,-87.63788,Entire home/apt,150,4,35,2019-05-15,0.56,11,280
4,10610,3 Comforts of Cooperative Living,2140,Lois And Ed,NaN,Hyde Park,41.79708,-87.59195,Private room,35,2,38,2019-04-12,0.68,5,240

In [21]:
listings_2.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,20190519023000,2019-05-19,Hyde Park - Walk to UChicago/Metra to McCormic...,"Be the sole guest in a quiet, vintage, 2nd flo...","The private bedroom has a queen size bed, ches...","Be the sole guest in a quiet, vintage, 2nd flo...",none,My apartment is located one block from beautif...,The basement laundry room hours are 8:00am to ...,UNIVERSITY OF CHICAGO: Visiting academics and ...,You will have access to the entire apartment (...,I will greet you when you arrive and show you ...,1. Your booking is for ONE (1) person only. Yo...,NaN,NaN,https://a0.muscache.com/im/pictures/acf6b3c0-4...,NaN,2613,https://www.airbnb.com/users/show/2613,Rebecca,2008-08-29,"Chicago, Illinois, United States",My 2 bdrm apartment is a 2nd floor walk-up in ...,within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/user/8bb47...,https://a0.muscache.com/im/pictures/user/8bb47...,Hyde Park,1.0,1.0,"['email', 'phone', 'reviews', 'manual_offline'...",t,t,"Chicago, IL, United States",Hyde Park,Hyde Park,NaN,Chicago,IL,60637,Chicago,"Chicago, IL",US,United States,41.78886,-87.58671,t,Condominium,Private room,1,1.0,1.0,1.0,Real Bed,"{TV,Wifi,Kitchen,""Free street parking"",Heating...",NaN,$50.00,$350.00,NaN,$0.00,$15.00,1,$0.00,2,89,2,2,89,89,2.0,89.0,3 weeks ago,t,15,39,61,316,2019-05-19,149,31,2015-01-09,2019-05-17,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,R17000015609,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",f,f,strict_14_with_grace_period,f,f,1,0,1,0,2.81
1,4505,https://www.airbnb.com/rooms/4505,20190519023000,2019-05-19,We're back. 365 Great Reviews. 1 bad one.,"We took the winter off, made things nicer arou...","We travel a lot, we know what people need. We...","We took the winter off, made things nicer arou...",none,NaN,NaN,The CTA train station is 30 yards (27 meters) ...,We also have a huge yard. Use it (weather perm...,NaN,Don't sit around all day watching T.V. Don't h...,NaN,NaN,https://a0.muscache.com/im/pictures/15019798/7...,NaN,5775,https://www.airbnb.com/users/show/5775,Craig & Kathleen,2008-12-29,"Chicago, Illinois, United States",Incredibly creative(Kathleen) and stunningly a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/5775/profile_...,https://a0.muscache.com/im/users/5775/profile_...,Little Village,1.0,1.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Chicago, IL, United States",Little Village,South Lawndale,NaN,Chicago,IL,60608,Chicago,"Chicago, IL",US,United States,41.85495,-87.69696,t,Apartment,Entire home/apt,7,1.0,3.0,4.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$117.00,$925.00,NaN,$0.00,$35.00,2,$25.00,2,60,2,2,60,60,2.0,60.0,yesterday,t,10,25,46,310,2019-05-19,368,23,2009-03-06,2019-05-05,96.0,10.0,10.0,10.0,10.0,9.0,9.0,t,R19000037538,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,moderate,f,f,1,1,0,0,2.96
2,7126,https://www.airbnb.com/rooms/7126,20190519023000,2019-05-19,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhood.,This is a very small studio apartment with a ...,A very small studio in a wonderful neighborhoo...,none,"Ukrainian Village was just named ""Hottest Neig...",We really like our neighbors and want guests t...,We are 1/2 mile away from the el train stop (b...,"You will be in your own private, tiny apartmen...",My family lives in the building but we are not...,This is a tiny apartment and is only appropria...,NaN,NaN,https://a0.muscache.com/im/pictures/51073/16c8...,NaN,17928,https://www.airbnb.com/users/show/17928,Sarah,2009-05-19,"Chicago, Illinois, United States",We live in Chicago. We love to travel and see ...,within an hour,100%,NaN,f,https://a0.muscache.com/im/users/17928/profile...,https://a0.muscache.com/im/users/17928/profile...,Ukrainian Village,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,f,"Chicago, IL, United States",Ukrainian Village,West Town,NaN,Chicago,IL,60622,Chicago,"Chicago, IL",US,United States,41.90289,-87.68182,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,Futon,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",NaN,$80.00,$600.00,NaN,$0.00,$0.00,1,$0.00,2,60,2,2,60,60,2.0,60.0,yesterday,t,7,23,38,309,2019-05-19,338,51,2009-07-03,2019-05-05,92.0,10.0,9.0,10.0,10.0,10.0,10.0,t,R18000034991,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",f,f,moderate,f,f,1,1,0,0,2.81
3,9811,https://www.airbnb.com/rooms/9811,20190519023000,2019-05-19,Barbara's Hideaway - Old Town,One-bedroom hideaway tucked into Old Town step...,"This lovely one bedroom ""hideaway"" is located ...",One-bedroom hideaway tucked into Old Town step...,none,Chicago’s Old Town neighborhood is squeezed be...,Vacation rental tax of 21.4 required in additi...,"Public transit in Chicago is excellent, and al...",NaN,We're always here for our guests. We have an ...,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/37df1935-8...,NaN,33004,https://www.airbnb.com/users/show/33004,At Home Inn,2009-08-21,"Chicago, Illinois, United States","Hi, we're Bob and Liz Biddle, long time Chicag...",within an hour,89%,NaN,f,https://a0.muscache.com/im/pictures/e23d4143-c...,https://a0.muscache.com/im/pictures/e23d4143-c...,Old Town,11.0,11.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Chicago, IL, United States",Old Town,Lincoln Park,NaN,Chicago,IL,60614,Chicago,"Chicago, IL",US,United States,41.91769,-87.63788,t,Apartment,Entire home/apt,4,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$150.00,"$1,050.00","$3,400.00",NaN,$95.00,2,$25.00,4,60,4,4,60,60,4.0,60.0,2 days ago,t,2,3,9,280,2019-05-19,35,15,2014-04-15,2019-05-15,92.0,9.0,9.0,10.0,9.0,10.0,9.0,t,2079260,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,strict_14_with_grace_period,f,f,11,11,0,0,0.56
4,10610,https://www.airbnb.com/rooms/10610,20190519023000,2019-05-19,3 Comforts of Cooperative Living,The condo is the 2nd floor in a lovely 1912 3-...,Newly furnished with queen bed and the comfort...,The condo is the 2nd floor in a lovely 1912 3-...,none,It's a 10 minute walk from the lakefront bike ...,If you stay longer than 21 days you are expect...,It is a short walk to public transportation th...,Pantry has non-perishable food for use by hous...,I travel a lot for work so you may not see me ...,No smoking in the condo. I only rent to adult...,NaN,NaN,https://a0.muscache.com/im/pictures/51944609/8...,NaN,2140,https://www.airbnb.com/users/show/2140,Lois And Ed,2008-08-16,"Aurora, Illinois, United States",Outgoing people who love people and exploring ...,within an hour,93%,NaN,f,https://a0.muscache.com/im/pictures/a8ba9bee-c...,https://a0.muscache.com/im/pictures/a8ba9bee-c...,Hyde Park,5.0,5.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Chicago, IL, United States",Hyde Park,Hyde Park,NaN,Chicago,IL,60615,Chicago,"Chicago, IL",US,United States,41.79708,-87.59195,t,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$35.00,$235.00,$805.00,$200.00,$50.00,1,$10.00,2,365,2,2,365,365,2.0,365.0,yesterday,t,7,37,61,240,2019-05-19,38,9,2014-10-25,2019-04-12,85.0,9.0,8.0,9.0,9.0,10.0,9.0,t,City registration pending,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,moderate,f,f,5,1,4,0,0.68

In [10]:
neighborhoods.head()

   neighbourhood_group   neighbourhood
0                  NaN     Albany Park
1                  NaN  Archer Heights
2                  NaN   Armour Square
3                  NaN         Ashburn
4                  NaN  Auburn Gresham

In [22]:
calendar.shape, reviews_1.shape, reviews_2.shape, listings.shape, listings_2.shape, neighborhoods.shape

((2981670, 7), (306085, 2), (306085, 6), (8169, 16), (8169, 106), (77, 2))

In [142]:
df = listings_2.drop([
'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary', 'space', 'description', 'experiences_offered',
'neighborhood_overview', 'notes', 'transit', 'access', 'interaction', 'house_rules', 'thumbnail_url', 'medium_url',
'picture_url', 'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url', 'host_picture_url', 'street', 'state', 'market',
'smart_location', 'country', 'square_feet', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60',
'availability_90', 'availability_365', 'calendar_last_scraped', 'first_review', 'last_review', 'license', 'jurisdiction_names',
'is_business_travel_ready', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes',
'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'host_verifications', 'host_has_profile_pic',
'host_identity_verified', 'host_listings_count', 'host_total_listings_count', 'host_response_time', 'host_response_rate',
'host_is_superhost', 'neighbourhood_group_cleansed', 'city', 'country_code', 'is_location_exact', 'monthly_price', 'minimum_nights',
'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights',
'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'requires_license', 'require_guest_profile_picture', 'require_guest_phone_verification',
'weekly_price', 'host_neighbourhood', 'number_of_reviews', 'number_of_reviews_ltm', 'review_scores_rating', 'review_scores_accuracy',
'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location',
'review_scores_value', 'instant_bookable', 'cancellation_policy', 'reviews_per_month', 'neighbourhood', 'neighbourhood_cleansed',
'latitude', 'longitude', 'guests_included', 'extra_people', 'security_deposit'], axis=1)

In [143]:
df.head()

,id,zipcode,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,cleaning_fee
0,2384,60637,Condominium,Private room,1,1.0,1.0,1.0,Real Bed,"{TV,Wifi,Kitchen,""Free street parking"",Heating...",$50.00,$15.00
1,4505,60608,Apartment,Entire home/apt,7,1.0,3.0,4.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$117.00,$35.00
2,7126,60622,Apartment,Entire home/apt,2,1.0,1.0,1.0,Futon,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",$80.00,$0.00
3,9811,60614,Apartment,Entire home/apt,4,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$150.00,$95.00
4,10610,60615,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$35.00,$50.00